package onebyone

import (
	"encoding/json"
	"strings"

	"github.com/beego/beego/v2/adapter/logs"
	"github.com/cdle/sillyGirl/core"
	"github.com/gin-gonic/gin"
)

type AutoGenerated struct {
	ptPin   string `json:"pt_pin"`
	message string `json:"message"`
}

func init() {

	logs.Info("开启一对一推送")
	core.Server.POST("/wx/push", func(c *gin.Context) {
		data, _ := c.GetRawData()
		ag := &AutoGenerated{}
		json.Unmarshal(data, ag)
		ptPin := ag.ptPin
		message := ag.message
		tp := "wx"
		core.Bucket("pin" + strings.ToUpper(tp)).Foreach(func(k, v []byte) error {
			if string(k) == ptPin && ptPin != "" {
				if push, ok := core.Pushs[tp]; ok {
					push(string(v), message, tp)
				}
			}
			return nil
		})
	})
}
